#+TITLE: pywm developer information

* Development
** Current (v0.2)
*** DONE Enable wayvnc.sh
*** STRT Update wlroots
- [X] Reenable wm_renderer
- [-] Keep an eye on Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1246834
  So long patch by undoing https://github.com/swaywm/wlroots/commit/d290b13871fa18dcad6cd90d9ee93e7205742124?diff=unified
*** STRT Multiple outputs
- [X] Accept config per output
- [X] wlr_surface_send_enter
- [X] Config per output from Python
- [X] Report detailed layout to python
- [X] Properly load xcursor
- [X] Handle scaling of motion properly (without pywm.width, pywm.height) and remove motion_absolute
- [X] Properly handle cursor on vnc - check what sway does
- [X] Render windows / widgets / mouse according to layout
- [X] Possibility to duplicate screen? or at least place windows (widgets also?) on multiple screens at the same time
- [X] Crashes on closing virtual outputs: Caused by removing (callback_update) an output during its present event
- [ ] Check valgrind for lost memory
- [X] Is pywm.round_scale necessary? Issues if set to 1 (write test cases)? Probably only sensible to scale according to logical pixels (round_scale == output_scale) or: positions according to lowest scaled monitor the content is on / width according to logical pixels
- [X] Get rid of pywm.output_scale, pywm.width, pywm.height
- [X] Fix widgets to one output ?! Useful if we have overlapping screens of different resolution?
*** Output transforms
*** Updatable config
*** Documentation / Update config keys

** Backlog / Ideas
*** Complete libinput device config / support for external mouse
*** Configurable gestures (abstraction layer) + possibility to use external "gesture providers" (e.g. detection from webcam video)
*** Support newm-sidecar (or similar, via ws://) as touchpad
*** Touch input from yoga or similar
*** Screensharing using xdg-desktop-portal-wlr
*** Decorations for floating windows (dialogs)


* Notes
- Depending on the settings (see newm) XWayland apps are responsible for handling HiDPI themselves and will per default appear very small
- GDK on XWayland: GDK_DPI_SCALE=2
- Electron apps: --force-device-scale-factor=2

- Screen record: wf-recorder
- Screen shot: grim
- Firefox: MOZ_ENABLE_WAYLAND=1
- Chromium: --enable-features=UseOzonePlatform --ozone-platform=wayland
- Matplotlib / Qt5 on Wayland requires DISPLAY=":0" to be set
- Apple Trackpad
        https://medium.com/macoclock/how-to-pair-apple-magic-keyboard-a1314-on-ubuntu-18-04-and-act-as-numpad-42fe4402454c
        https://wiki.archlinux.org/index.php/Bluetooth
